// Generated by LiveScript 1.2.0
var mapOption, coordCtrl;
mapOption = {
  center: new google.maps.LatLng(23.745126, 120.926514),
  zoom: 8,
  minZoom: 8,
  maxZoom: 18,
  mapTypeId: google.maps.MapTypeId.ROADMAP
};
coordCtrl = function($scope){
  import$($scope, {
    twd97: {},
    gws84: {},
    byWatch: false,
    map: new google.maps.Map(document.getElementById('map-view'), mapOption),
    updateMapTimer: null,
    updateMap: function(){
      if (this.updateMapTimer) {
        clearTimeout(this.updateMapTimer);
      }
      return this.updateMapTimer = setTimeout(function(){
        return $scope.$apply(function(){
          $scope.updateMapTimer = null;
          $scope.map.setCenter(new google.maps.LatLng($scope.gws84.y, $scope.gws84.x));
          return google.maps.event.addListenerOnce($scope.map, 'idle', function(){
            return google.maps.event.trigger($scope.map, 'resize');
          });
        });
      }, 1000);
    }
  });
  $scope.$watch('twd97.x + twd97.y', function(){
    var laglng, ref$;
    if ($scope.byWatch) {
      return $scope.byWatch = false;
    } else {
      $scope.byWatch = true;
    }
    ref$ = laglng = coord.toGws84($scope.twd97.x, $scope.twd97.y), $scope.gws84.x = ref$.lng, $scope.gws84.y = ref$.lat;
    if ($scope.gws84.x && $scope.gws84.y) {
      return $scope.updateMap();
    }
  });
  return $scope.$watch('gws84.x + gws84.y', function(){
    var ref$;
    if ($scope.byWatch) {
      return $scope.byWatch = false;
    } else {
      $scope.byWatch = true;
    }
    ref$ = coord.toTwd97({
      lat: $scope.gws84.y,
      lng: $scope.gws84.x
    }), $scope.twd97.x = ref$[0], $scope.twd97.y = ref$[1];
    if ($scope.gws84.x && $scope.gws84.y) {
      return $scope.updateMap();
    }
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}